StereoCamera Class Reference
The base class defining stereo camera.
#include <stereoCamera.h>
Public Member Functions
StereoCamera (bool rectify=true)
Default Constructor.
StereoCamera (yarp::os::ResourceFinder &rf, bool rectify=true)
Costructor for initialization from file.
StereoCamera (Camera First, Camera Second, bool rectify=true)
Constructor for initialization using two calibrated cameras.
void initELAS (yarp::os::ResourceFinder &rf)
Initialization of ELAS parameters.
void stereoCalibration (vector< string > imageList, int boardWidth, int boardHeight, float sqsize=1.0)
It performs the stereo camera calibration.
void saveCalibration (string extrinsicFilePath, string intrinsicFilePath)
It saves the calibration.
void setImages (const Mat &firstImg, const Mat &secondImg)
It stores in memory a couple of images.
cv::Mat findMatch (bool visualize=false, double displacement=20.0, double radius=200.0)
It finds matches between two images.
void computeDisparity (bool best=true, int uniquenessRatio=15, int speckleWindowSize=50, int speckleRange=16, int numberOfDisparities=64, int SADWindowSize=7, int minDisparity=0, int preFilterCap=63, int disp12MaxDiff=0)
It computes the Disparity Map (see stereoDisparity).
void undistortImages ()
It undistorts the images.
void horn (Mat &K1, Mat &K2, vector< Point2f > &Points1, vector< Point2f > &Points2, Mat &Rot, Mat &Tras)
It performs the horn relative orientations algorithm i.e.
void hornRelativeOrientations ()
It performs the horn relative orientations, all the parameters are assumed initialized in the StereoCamera object.
Point3f triangulation (Point2f &point1, Point2f &point2)
It performs the triangulation using the stored in the internal P1 and P2 3x4 Camera Matrices.
Point3f triangulation (Point2f &point1, Point2f &point2, Mat Camera1, Mat Camera2)
It performs the triangulation (HZ Chap 12.2 homogenous solution).
Point3f triangulationLS (Point2f &point1, Point2f &point2, Mat Camera1, Mat Camera2)
It performs the least square triangulation (HZ Chap 12.2 Inhomogenous solution).
Point3f metricTriangulation (Point2f &point1, double thMeters=10)
It performs the metric triangulation given the pixel coordinates on the first image.
Point3f metricTriangulation (Point2f &point1, Mat &H, double thMeters=10)
It performs the metric triangulation given the pixel coordinates on the first image.
Point3f triangulateKnownDisparity (float u, float v, float d, Mat &H)
It performs the metric triangulation given the pixel coordinates on the first image and the disparity between the two RECTIFIED images.
void estimateEssential ()
It estimates the essential matrix (3x3) E between two views.
bool essentialDecomposition ()
It decomposes the essential matrix in Rotation and Translation between the two views.
void chierality (Mat &R1, Mat &R2, Mat &t1, Mat &t2, Mat &R, Mat &t, vector< Point2f > points1, vector< Point2f > points2)
It performs the chierality test: given a couple of rotation matrices, translation vectors and matches it finds the correct rotation and translation s.t.
const Mat & getImLeft () const
It returns the left (first) image.
const Mat & getImRight () const
It returns the right (second) image.
const Mat & getImLeftUnd () const
It returns the left undistorted image.
const Mat & getImRightUnd () const
It returns the right undistorted image.
const Mat & getDisparity () const
It returns the disparity image.
const Mat & getDisparity16 () const
It returns the disparity image.
const Mat & getQ () const
It returns the 4x4 disparity-to-depth mapping matrix.
const Mat & getKleft () const
It returns the 3x3 left camera matrix.
const Mat & getKright () const
It returns the 3x3 right camera matrix.
const Mat & getFundamental () const
It returns the 3x3 fundamental matrix.
const vector< Point2f > & getMatchLeft () const
It returns the pixel coordinates of the matches in the left image.
const vector< Point2f > & getMatchRight () const
It returns the pixel coordinates of the matches in the right image.
const Mat & getTranslation () const
It returns the translation vector between the two cameras.
const Mat & getRotation () const
It returns the rotation matrix between the two cameras.
const Mat & getMapperL () const
It returns the mapping between the original left camera and the rectified left camera.
const Mat & getMapperR () const
It returns the mapping between the original right camera and the rectified right camera.
const Mat & getRLrect () const
It returns the rotation matrix between the original left camera and the rectified left camera.
const Mat & getRRrect () const
It returns the rotation matrix between the original right camera and the rectified right camera.
void setRotation (Mat &Rot, int mode=0)
It sets the rotation matrix (if known) between the first and the second camera.
void setTranslation (Mat &Tras, int mul=0)
It sets the translation vector (if known) between the first and the second camera.
void setIntrinsics (Mat &K1, Mat &K2, Mat &Dist1, Mat &Dist2)
It sets the intrinsic parameters.
void rectifyImages ()
The method rectifies the two images: it transform each image plane such that pairs conjugate epipolar lines become collinear and parallel to one of the image axes (i.e.
const Mat & getLRectified () const
The method returns the first rectified image.
const Mat & getRRectified () const
The method returns the second rectified image.
vector< Point2f > projectPoints3D (string camera, vector< Point3f > &points3D, Mat &H)
The method returns the 2D projection of a set of 3D points in the cartesian space to the specified camera.
Mat computeWorldImage (Mat &H)
The method returns a 3-Channels float image with the world coordinates w.r.t H reference system.
const Mat & getDistCoeffRight () const
It returns the 5x1 right distortion coefficients.
const Mat & getDistCoeffLeft () const
It returns the 5x1 left distortion coefficients.
Point2f getDistortedPixel (int u, int v, int cam=1)
Given the u,v pixel coordinates in the undistorted image the method returns the original position of the pixel in the distorted frame.
Mat drawMatches ()
The method returns a 3-Channels 8bit image with the image matches.
void setMatches (std::vector< cv::Point2f > &pointsL, std::vector< cv::Point2f > &pointsR)
The function initialize the matches of the current image pair.
void setExpectedPosition (Mat &Rot, Mat &Tran)
The function set the expected Rotation and Translation parameters for the current image pair.
Mat FfromP (Mat &P1, Mat &P2)
The function computes the fundamental matrix starting from known camera matrices.
Point2f fromRectifiedToOriginal (int u, int v, int camera)
Given the u,v pixel coordinates in the rectified image the method returns the position of the pixel in the non-rectified frame.
cv::Mat remapDisparity (cv::Mat disp)
Remaps the disparity map on the basis of the mapping previously computed.
void updateMappings ()
XXXXXXXXXXXXXXXXXXXX.
Data Fields
Mat filtered_disp
Detailed Description
The base class defining stereo camera.
It allows to calibrate the cameras, to undistort a pair of images, to find matches between two images, to triangulate points and to estimate motion between two images. The basic assumption is that the two images come from a stereo camera, however this class works also with two arbitrary images.
Definition at line 91 of file stereoCamera.h.
Constructor & Destructor Documentation
StereoCamera() [1/3]
StereoCamera::StereoCamera (bool rectify = true)
Default Constructor.
You should initialize all the intrinsic and extrinsic parameters using the provided methods.
Definition at line 116 of file stereoCamera.cpp.
                                       {
    this->rectify=rectify;
    this->epipolarTh=0.01;
    this->cameraChanged = true;
#if !defined(USING_GPU) && !defined(OPENCV_GREATER_2)
    cv::initModule_nonfree();
#endif
}
StereoCamera() [2/3]
StereoCamera::StereoCamera (yarp::os::ResourceFinder & rf, bool rectify = true)
Costructor for initialization from file.
Parameters
rf is the config file generated by the stereoCalib module.
Definition at line 128 of file stereoCamera.cpp.
References setIntrinsics(), setRotation(), and setTranslation().
                                                                 {
    Mat KL, KR, DistL, DistR, R, T;
    loadStereoParameters(rf,KL,KR,DistL,DistR,R,T);
    this->setIntrinsics(KL,KR,DistL,DistR);
    this->setRotation(R,0);
    this->setTranslation(T,0);
    this->cameraChanged=true;
    this->epipolarTh=0.01;
    this->rectify=rectify;
    buildUndistortRemap();
#if !defined(USING_GPU) && !defined(OPENCV_GREATER_2)
    cv::initModule_nonfree();
#endif
}
StereoCamera() [3/3]
StereoCamera::StereoCamera (Camera First, Camera Second, bool rectify = true)
Constructor for initialization using two calibrated cameras.
Note
Only intrinsic parameters are initialized.
Parameters
First the first camera (Left eye is assumed but you can use any arbitrary camera). The 3D point coordinates have this reference system.
Second the second camera (Right eye is assumed).
Definition at line 147 of file stereoCamera.cpp.
References Camera::getCameraMatrix(), and Camera::getDistVector().
                                                                 {
    this->Kleft=Left.getCameraMatrix();
    this->DistL=Left.getDistVector();
    this->Kright=Right.getCameraMatrix();
    this->DistR=Right.getDistVector();
    this->cameraChanged=true;
    this->rectify=rectify;
    this->epipolarTh=0.01;
    buildUndistortRemap();
#if !defined(USING_GPU) && !defined(OPENCV_GREATER_2)
    cv::initModule_nonfree();
#endif
}
Member Function Documentation
chierality()
void StereoCamera::chierality (Mat & R1, Mat & R2, Mat & t1, Mat & t2, Mat & R, Mat & t, vector< Point2f > points1, vector< Point2f > points2)
It performs the chierality test: given a couple of rotation matrices, translation vectors and matches it finds the correct rotation and translation s.t.
the triangulated points have their depth coordinates greater than 0. The method is used by essentialDecomposition, indeed an essential matrix generates 2 rotations and 2 translation. The chierality test is needed in order to discard wrong rototranslations.
Parameters
R1 first rotation 3x3 matrix
R2 second rotation 3x3 matrix
t1 first translation 3x1 matrix
t2 second translation 3x1 matrix
R output rotation matrix
t output translation matrix
points1 corrispondences in the first image
points2 corrispondences in the second image
Definition at line 1171 of file stereoCamera.cpp.
References triangulation().
Referenced by essentialDecomposition().
                                                                                                           
                                 {
    Mat A= Mat::eye(3,4,CV_64FC1);
    Mat P1 = this->Kleft*Mat::eye(3, 4, CV_64F);
    for(int i = 0; i < R1.rows; i++)
    {
        double* Mi = A.ptr<double>(i);
        double* MRi = R1.ptr<double>(i);
        for(int j = 0; j < R1.cols; j++)
            Mi[j]=MRi[j];
    }
    for(int i = 0; i < t1.rows; i++)
    {
        double* Mi = A.ptr<double>(i);
        double* MRi = t1.ptr<double>(i);
        Mi[3]=MRi[0];
    }
    Mat P2=this->Kright*A;
    A= Mat::eye(3,4,CV_64FC1);
    for(int i = 0; i < R2.rows; i++)
    {
        double* Mi = A.ptr<double>(i);
        double* MRi = R2.ptr<double>(i);
        for(int j = 0; j < R2.cols; j++)
            Mi[j]=MRi[j];
    }
    for(int i = 0; i < t2.rows; i++)
    {
        double* Mi = A.ptr<double>(i);
        double* MRi = t2.ptr<double>(i);
        Mi[3]=MRi[0];
    }
    Mat P3=this->Kright*A;
    A= Mat::eye(3,4,CV_64FC1);
    for(int i = 0; i < R1.rows; i++)
    {
        double* Mi = A.ptr<double>(i);
        double* MRi = R1.ptr<double>(i);
        for(int j = 0; j < R1.cols; j++)
            Mi[j]=MRi[j];
    }
    for(int i = 0; i < t1.rows; i++)
    {
        double* Mi = A.ptr<double>(i);
        double* MRi = t2.ptr<double>(i);
        Mi[3]=MRi[0];
    }
    Mat P4=this->Kright*A;
    A= Mat::eye(3,4,CV_64FC1);
    for(int i = 0; i < R2.rows; i++)
    {
        double* Mi = A.ptr<double>(i);
        double* MRi = R2.ptr<double>(i);
        for(int j = 0; j < R2.cols; j++)
            Mi[j]=MRi[j];
    }
    for(int i = 0; i < t2.rows; i++)
    {
        double* Mi = A.ptr<double>(i);
        double* MRi = t1.ptr<double>(i);
        Mi[3]=MRi[0];
    }
    Mat P5=this->Kright*A;
    int err1=0; //R1 t1
    int err2=0; //R2 t2
    int err3=0; //R1 t2
    int err4=0; //R2 t1
    Mat point(4,1,CV_64FC1);
    for(int i=0; i<(int) InliersL.size(); i++)
    {
        Point3f point3D=triangulation(points1[i],points2[i],P1,P2);
        Mat H1=buildRotTras(R1,t1);
        point.at<double>(0,0)=point3D.x;
        point.at<double>(1,0)=point3D.y;
        point.at<double>(2,0)=point3D.z;
        point.at<double>(0,0)=1.0;
        Mat rotatedPoint=H1*point;
        //fprintf(stdout, "Camera P2 Point3D: %f %f %f Rotated Point: %f %f %f \n",
       point3D.x,point3D.y,point3D.z, rotatedPoint.at<double>(0,0),rotatedPoint.at<double>(1,0),rotatedPoint.at<double>(2,0));
        if(point3D.z<0 || rotatedPoint.at<double>(2,0)<0) {
            err1++;
        }
        point3D=triangulation(points1[i],points2[i],P1,P3);
        Mat H2=buildRotTras(R2,t2);
        point.at<double>(0,0)=point3D.x;
        point.at<double>(1,0)=point3D.y;
        point.at<double>(2,0)=point3D.z;
        point.at<double>(0,0)=1.0;
        rotatedPoint=H2*point;
        //fprintf(stdout, "Camera P3 Point3D: %f %f %f Rotated Point: %f %f %f \n",
       point3D.x,point3D.y,point3D.z, rotatedPoint.at<double>(0,0),rotatedPoint.at<double>(1,0),rotatedPoint.at<double>(2,0));
        if(point3D.z<0 || rotatedPoint.at<double>(2,0)<0) {
            err2++;
        }
        point3D=triangulation(points1[i],points2[i],P1,P4);
        Mat H3=buildRotTras(R1,t2);
        point.at<double>(0,0)=point3D.x;
        point.at<double>(1,0)=point3D.y;
        point.at<double>(2,0)=point3D.z;
        point.at<double>(0,0)=1.0;
        rotatedPoint=H3*point;
        //fprintf(stdout, "Camera P4 Point3D: %f %f %f Rotated Point: %f %f %f \n",
       point3D.x,point3D.y,point3D.z, rotatedPoint.at<double>(0,0),rotatedPoint.at<double>(1,0),rotatedPoint.at<double>(2,0));
        if(point3D.z<0 || rotatedPoint.at<double>(2,0)<0) {
            err3++;
        }
        point3D=triangulation(points1[i],points2[i],P1,P5);
        Mat H4=buildRotTras(R2,t1);
        point.at<double>(0,0)=point3D.x;
        point.at<double>(1,0)=point3D.y;
        point.at<double>(2,0)=point3D.z;
        point.at<double>(0,0)=1.0;
        rotatedPoint=H4*point;
        //fprintf(stdout, "Camera P5 Point3D: %f %f %f Rotated Point: %f %f %f \n",
       point3D.x,point3D.y,point3D.z, rotatedPoint.at<double>(0,0),rotatedPoint.at<double>(1,0),rotatedPoint.at<double>(2,0));
        if(point3D.z<0 || rotatedPoint.at<double>(2,0)<0) {
            err4++;
        }
    }
    /*printMatrix(R1);
    printMatrix(t1);
    printMatrix(R2);
    printMatrix(t2);*/
    //fprintf(stdout, "Inliers: %d, %d, \n",points1.size(),points2.size());
    //fprintf(stdout, "errors: %d, %d, %d, %d, \n",err1,err2,err3,err4);
    double minErr=10000;
    double secondErr=minErr;
    int idx=0;
    if(err1<minErr && t1.ptr<double>(0)[0]<0)
    {
        idx=1;
        secondErr=minErr;
        minErr=err1;
    }
    if(err2<minErr && t2.ptr<double>(0)[0]<0)
    {
        idx=2;
        secondErr=minErr;
        minErr=err2;
    }
    if(err3<minErr && t2.ptr<double>(0)[0]<0)
    {
        idx=3;
        secondErr=minErr;
        minErr=err3;
    }
    if(err4<minErr && t1.ptr<double>(0)[0]<0)
    {
        idx=4;
        secondErr=minErr;
        minErr=err4;
    }
    /*if(secondErr==minErr)
      {
        R=this->R;
        t=this->T;
        return;
      }*/
    if(idx==1) {
        R=R1;
        t=t1;
        return;
    }
    if(idx==2) {
        R=R2;
        t=t2;
        return;
    }
    if(idx==3) {
        R=R1;
        t=t2;
        return;
    }
    if(idx==4) {
        R=R2;
        t=t1;
        return;
    }
}
computeDisparity()
void StereoCamera::computeDisparity (bool best = true, int uniquenessRatio = 15, int speckleWindowSize = 50, int speckleRange = 16, int numberOfDisparities = 64, int SADWindowSize = 7, int minDisparity = 0, int preFilterCap = 63, int disp12MaxDiff = 0)
It computes the Disparity Map (see stereoDisparity).
Parameters
best set equal true for better accuracy, equal false for save computation.
uniquenessRatio The margin in percents by which the best (minimum) computed cost function value should win the second best value to consider the found match correct. Normally, some value within 5-15 range is good enough.
speckleWindowSize Maximum size of smooth disparity regions to consider them noise speckles and invdalidate. Set it to 0 to disable speckle filtering. Otherwise, set it somewhere in 50-200 range.
speckleRange Maximum disparity variation within each connected component. If you do speckle filtering, set it to some positive value, multiple of 16. Normally, 16 or 32 is good enough.
Note
Run the calibration or set all the parameters before using this method.
Definition at line 581 of file stereoCamera.cpp.
{
    if (this->Kleft.empty() || this->DistL.empty() || this->Kright.empty() || this->DistR.empty())
    {
        cout <<" Cameras are not calibrated! Run the Calibration first!" << endl;
        return;
    }
    if (this->imleft.empty() || this->imright.empty())
    {
        cout << "Images are not set! set the images first!" << endl;
        return;
    }
    Size img_size=this->imleft.size();
    if (cameraChanged)
    {
        lock_guard<mutex> lg(mtx);
        stereoRectify(this->Kleft, this->DistL, this->Kright, this->DistR, img_size,
                this->R, this->T, this->RLrect, this->RRrect, this->PLrect,
                this->PRrect, this->Q, -1);
        if (!rectify)
        {
            this->RLrect=Mat::eye(3,3,CV_32FC1);
            this->RRrect=Mat::eye(3,3,CV_32FC1);
            this->PLrect=this->Kleft;
            this->PRrect=this->Kright;
        }
    }
    if (cameraChanged)
    {
        initUndistortRectifyMap(this->Kleft, this->DistL, this->RLrect, this->PLrect,
                img_size, CV_32FC1, this->map11, this->map12);
        initUndistortRectifyMap(this->Kright, this->DistR, this->RRrect, this->PRrect,
                img_size, CV_32FC1, this->map21, this->map22);
    }
    Mat img1r, img2r;
    remap(this->imleft, img1r, this->map11, this->map12, cv::INTER_LINEAR);
    remap(this->imright, img2r, this->map21,this->map22, cv::INTER_LINEAR);
    imgLeftRect = img1r;
    imgRightRect = img2r;
    Mat disp,disp8,map,dispTemp;
    bool success;
    if (use_elas)
    {
        success = elaswrap->compute_disparity(img1r, img2r, disp, numberOfDisparities);
        if (success)
        {
            map = disp * (255.0 / numberOfDisparities);
            //threshold(map, map, 0, 255.0, THRESH_TOZERO);
        }
    } else
    {
        int cn=this->imleft.channels();
    #ifdef OPENCV_GREATER_2
        Ptr<StereoSGBM> sgbm=cv::StereoSGBM::create(minDisparity,numberOfDisparities,SADWindowSize,
                                                    8*cn*SADWindowSize*SADWindowSize,
                                                    32*cn*SADWindowSize*SADWindowSize,
                                                    disp12MaxDiff,preFilterCap,uniquenessRatio,
                                                    speckleWindowSize,speckleRange,
                                                    best?StereoSGBM::MODE_HH:StereoSGBM::MODE_SGBM);
        sgbm->compute(img1r, img2r, disp);
    #else
        StereoSGBM sgbm;
        sgbm.preFilterCap = preFilterCap; //63
        sgbm.SADWindowSize = SADWindowSize;
        sgbm.P1 = 8*cn*SADWindowSize*SADWindowSize;
        sgbm.P2 = 32*cn*SADWindowSize*SADWindowSize;
        sgbm.minDisparity = minDisparity; //-15
        sgbm.numberOfDisparities = numberOfDisparities;
        sgbm.uniquenessRatio = uniquenessRatio; //22
        sgbm.speckleWindowSize = speckleWindowSize; //100
        sgbm.speckleRange = speckleRange; //32
        sgbm.disp12MaxDiff = disp12MaxDiff;
        sgbm.fullDP = best; // alg == STEREO_HH
        sgbm(img1r, img2r, disp);
    #endif
        disp.convertTo(map, CV_32FC1, 1.0,0.0);
        map.convertTo(map,CV_32FC1,255/(numberOfDisparities*16.));
        //normalize(map,map, 0, 255, cv::NORM_MINMAX, CV_8UC1);
        success = true;
    }
    if (success)
    {
        if (cameraChanged)
        {
            lock_guard<mutex> lg(mtx);
            Mat inverseMapL(map.rows*map.cols,1,CV_32FC2);
            Mat inverseMapR(map.rows*map.cols,1,CV_32FC2);
            for (int y=0; y<map.rows; y++)
            {
                for (int x=0; x<map.cols; x++)
                {
                    inverseMapL.ptr<float>(y*map.cols+x)[0]=(float)x;
                    inverseMapL.ptr<float>(y*map.cols+x)[1]=(float)y;
                    inverseMapR.ptr<float>(y*map.cols+x)[0]=(float)x;
                    inverseMapR.ptr<float>(y*map.cols+x)[1]=(float)y;
                }
            }
            undistortPoints(inverseMapL,inverseMapL,this->Kleft,this->DistL,this->RLrect,this->PLrect);
            undistortPoints(inverseMapR,inverseMapR,this->Kright,this->DistR,this->RRrect,this->PRrect);
            Mat mapperL=inverseMapL.reshape(2,map.rows);
            Mat mapperR=inverseMapR.reshape(2,map.rows);
            this->MapperL=mapperL;
            this->MapperR=mapperR;
            cameraChanged = false;
        }
        Mat x;
        remap(map,dispTemp,this->MapperL,x,cv::INTER_LINEAR);
        dispTemp.convertTo(disp8,CV_8U);
        if (use_elas)
            disp.convertTo(disp, CV_16SC1, 16.0);
    }
    lock_guard<mutex> lg(mtx);
    this->Disparity = disp8;
    this->Disparity16 = disp;
}
computeWorldImage()
Mat StereoCamera::computeWorldImage (Mat & H)
The method returns a 3-Channels float image with the world coordinates w.r.t H reference system.
Parameters
H the transformation from the camera reference system to the H reference system
Returns
The 3-Channels float image with the world coordinates w.r.t H reference system.
Definition at line 2231 of file stereoCamera.cpp.
References getRLrect().
{
    Mat worldImg(Disparity16.rows,Disparity16.cols,CV_32FC3);
    if(H.empty())
        H=H.eye(4,4,CV_64FC1);
    if(Disparity16.empty() || MapperL.empty() || Q.empty())
    {
        cout <<" Run computeDisparity() method first" << endl;
        return worldImg;
    }
    Mat dispTemp;
    Mat x;
    remap(this->Disparity16,dispTemp,this->MapperL,x,cv::INTER_LINEAR);
    reprojectImageTo3D(dispTemp, worldImg,this->Q,true);
    for(int i=0; i<worldImg.rows; i++)
    {
        for(int j=0; j<worldImg.cols; j++)
        {
            Mat RLrectTmp=this->getRLrect().t();
            Mat Tfake = Mat::zeros(0,3,CV_64F);
            Mat P(4,1,CV_64FC1);
            if((worldImg.data + worldImg.step * i)[j * worldImg.channels() + 2]>100)
            {
                P.at<double>(0,0)=0.0;
                P.at<double>(1,0)=0.0;
                P.at<double>(2,0)=0.0;
                P.at<double>(3,0)=1.0;
            }
            else
            {
                P.at<double>(0,0)=(worldImg.data + worldImg.step * i)[j * worldImg.channels() + 0];
                P.at<double>(1,0)=(worldImg.data + worldImg.step * i)[j * worldImg.channels() + 1];
                P.at<double>(2,0)=(worldImg.data + worldImg.step * i)[j * worldImg.channels() + 2];
                P.at<double>(3,0)=1;
                Mat Hrect=buildRotTras(RLrectTmp,Tfake);
                P=H*Hrect*P;
            }
            (worldImg.data + worldImg.step * i)[j * worldImg.channels() + 0]=(float) ((float) P.at<double>(
      0,0)/P.at<double>(3,0));
            (worldImg.data + worldImg.step * i)[j * worldImg.channels() + 1]=(float) ((float) P.at<double>(
      1,0)/P.at<double>(3,0));
            (worldImg.data + worldImg.step * i)[j * worldImg.channels() + 2]=(float) ((float) P.at<double>(
      2,0)/P.at<double>(3,0));
        }
    }
    return worldImg;
}
drawMatches()
Mat StereoCamera::drawMatches ()
The method returns a 3-Channels 8bit image with the image matches.
Returns
The 3-Channels 8bit image with the image matches. Call findMatch() to retrieve the keypoints first.
Definition at line 1668 of file stereoCamera.cpp.
{
    if (this->imleftund.empty() || this->imrightund.empty())
    {
        imleftund=imleft;
        imrightund=imright;
    }
    Mat matchImg;
    vector<KeyPoint> keypoints1(InliersL.size());
    vector<KeyPoint> keypoints2(InliersL.size());
    vector<DMatch> filteredMatches(InliersL.size());
    for (int i=0; i<InliersL.size(); i++)
    {
        filteredMatches[i].queryIdx=i;
        filteredMatches[i].trainIdx=i;
        keypoints1[i]=cv::KeyPoint(InliersL[i],2);
        keypoints2[i]=cv::KeyPoint(InliersR[i],2);
    }
    cv::drawMatches(this->imleftund,keypoints1,this->imrightund,keypoints2,
            filteredMatches,matchImg,Scalar(0,0,255,0),Scalar(0,0,255,0));
    return matchImg;
}
essentialDecomposition()
bool StereoCamera::essentialDecomposition ()
It decomposes the essential matrix in Rotation and Translation between the two views.
The output is stored in the private members R and T.
Definition at line 1071 of file stereoCamera.cpp.
References chierality().
{
    if (E.empty())
    {
        cout << "Essential Matrix is empty! Run the estimateEssential first!" << endl;
        return false;
    }
    if (this->InliersL.empty())
    {
        cout << "No matches in memory! Run findMatch first!" << endl;
        return false;
    }
    Mat W=Mat(3,3,CV_64FC1);
    W.setTo(0);
    W.at<double>(0,0)=0;
    W.at<double>(0,1)=-1;
    W.at<double>(0,2)=0;
    W.at<double>(1,0)=1;
    W.at<double>(1,1)=0;
    W.at<double>(1,2)=0;
    W.at<double>(2,0)=0;
    W.at<double>(2,1)=0;
    W.at<double>(2,2)=1;
    SVD dec(E);
    Mat Y=Mat::eye(3,3,CV_64FC1);
    Y.at<double>(2,2)=0.0;
    E=dec.u*Y*dec.vt; // projection to the Essential Matrix space
    dec(E);
    Mat V=dec.vt;
    Mat U=dec.u;
    Mat R1=U*W*V;
    Mat R2=U*W.t()*V;
    if (determinant(R1)<0 || determinant(R2)<0)
    {
        E=-E;
        SVD dec2(E);
        V=dec2.vt;
        U=dec2.u;
        R1=U*W*V;
        R2=U*W.t()*V;
    }
    Mat t1=U(Range(0,3),Range(2,3));
    Mat t2=-t1;
    Mat Rnew=Mat(3,3,CV_64FC1);
    Rnew.setTo(0);
    Mat tnew=Mat(3,1,CV_64FC1);
    chierality(R1,R2,t1,t2,Rnew,tnew,this->InliersL,this->InliersR);
    Mat rvec_new=Mat::zeros(3,1,CV_64FC1);
    Mat rvec_exp=Mat::zeros(3,1,CV_64FC1);
    Rodrigues(Rnew,rvec_new);
    Rodrigues(R_exp,rvec_exp);
    Mat t_est=(tnew/norm(tnew))*norm(this->T);
    Mat diff_angles=rvec_exp-rvec_new;
    Mat diff_tran=T_exp-t_est;
    std::cout << "[StereoCamera] Angles Differences: " << diff_angles.at<double>(0,0) << " " <<
                                                          diff_angles.at<double>(1,0) << " " <<
                                                          diff_angles.at<double>(2,0) << std::endl;
    std::cout << "[StereoCamera] Translation Differences: " << diff_tran.at<double>(0,0) << " " <<
                                                               diff_tran.at<double>(1,0) << " " <<
                                                               diff_tran.at<double>(2,0) << std::endl;
    // Magic numbers: rvec_new are the rotation angles, only vergence (rvec_new(1,0)) is allowed to be
       large
    // t_est is the translation estimated, it can change a little bit when joint 4 of the head is moving
    if (fabs(diff_angles.at<double>(0,0))<0.15 && fabs(diff_angles.at<double>(1,0))<0.15 && fabs(
      diff_angles.at<double>(2,0))<0.15 &&
            fabs(diff_tran.at<double>(0,0))<0.01 && fabs(diff_tran.at<double>(1,0))<0.01 && fabs(diff_tran
      .at<double>(2,0))<0.01)
    {
        lock_guard<mutex> lg(mtx);
        this->R=Rnew;
        this->T=t_est;
        this->updatePMatrix();
        this->cameraChanged=true;
        return true;
    }
    else
        return false;
}
estimateEssential()
void StereoCamera::estimateEssential ()
It estimates the essential matrix (3x3) E between two views.
The output is stored in the private member E.
Definition at line 965 of file stereoCamera.cpp.
References FfromP().
{
    this->InliersL.clear();
    this->InliersR.clear();
    if (this->PointsL.size()<10 || this->PointsL.size()<10)
    {
        cout << "Not enough matches in memory! Run findMatch first!" << endl;
        this->E=Mat(3,3,CV_64FC1);
        return;
    }
    updateExpectedCameraMatrices();
    Mat F_exp=FfromP(Pleft_exp,Pright_exp);
    vector<Point2f> filteredL;
    vector<Point2f> filteredR;
    std::cout << "[StereoCamera] " << PointsR.size() << " Matches Found." << std::endl;
    Mat pl=Mat(3,1,CV_64FC1);
    Mat pr=Mat(3,1,CV_64FC1);
    for (size_t i=0; i<(int) PointsL.size(); i++)
    {
        pl.at<double>(0,0)=PointsL[i].x;
        pl.at<double>(1,0)=PointsL[i].y;
        pl.at<double>(2,0)=1;
        pr.at<double>(0,0)=PointsR[i].x;
        pr.at<double>(1,0)=PointsR[i].y;
        pr.at<double>(2,0)=1;
        Mat xrFxl=pr.t()*F_exp*pl;
        Mat Fxl=F_exp*pl;
        Mat Fxr=F_exp.t()*pr;
        pow(xrFxl,2,xrFxl);
        pow(Fxl,2,Fxl);
        pow(Fxr,2,Fxr);
        Scalar den1,den2;
        den1=sum(Fxl);
        den2=sum(Fxr);
        double sampsonDistance=xrFxl.at<double>(0,0)/(den1.val[0]+den2.val[0]);
        if (sampsonDistance<0.1)
        {
            filteredL.push_back(PointsL[i]);
            filteredR.push_back(PointsR[i]);
        }
    }
    std::cout << "[StereoCamera] " << filteredL.size() << " Matches Left After Kinematics Filtering." <<
      std::endl;
    vector<uchar> status;
    this->F=findFundamentalMat(Mat(filteredL), Mat(filteredR), status, CV_FM_8POINT, 1, 0.999);
    for (size_t i=0; i<(int) filteredL.size(); i++)
    {
        pl.at<double>(0,0)=filteredL[i].x;
        pl.at<double>(1,0)=filteredL[i].y;
        pl.at<double>(2,0)=1;
        pr.at<double>(0,0)=filteredR[i].x;
        pr.at<double>(1,0)=filteredR[i].y;
        pr.at<double>(2,0)=1;
        Mat xrFxl=pr.t()*F*pl;
        Mat Fxl=F*pl;
        Mat Fxr=F.t()*pr;
        pow(xrFxl,2,xrFxl);
        pow(Fxl,2,Fxl);
        pow(Fxr,2,Fxr);
        Scalar den1,den2;
        den1=sum(Fxl);
        den2=sum(Fxr);
        if (status[i]==1 && xrFxl.at<double>(0,0)<0.001)
        {
            InliersL.push_back(filteredL[i]);
            InliersR.push_back(filteredR[i]);
        }
    }
    std::cout << "[StereoCamera] " << InliersL.size() << " Matches Left After RANSAC Filtering." <<
      std::endl;
    if (this->InliersL.size()<10 || this->InliersR.size()<10)
    {
        InliersL.clear();
        InliersR.clear();
        cout << "Not enough matches in memory! Run findMatch first!" << endl;
        this->E=Mat(3,3,CV_64FC1);
        return;
    }
    this->F=findFundamentalMat(Mat(InliersL), Mat(InliersR),status, CV_FM_8POINT, 1, 0.999);
    this->E=this->Kright.t()*this->F*this->Kleft;
}
FfromP()
Mat StereoCamera::FfromP (Mat & P1, Mat & P2)
The function computes the fundamental matrix starting from known camera matrices.
Parameters
P1 a 3x4 matrix representing the camera matrix of the left view.
P2 a 3x4 matrix representing the camera matrix of the right view.
Returns
a 3x3 matrix representing the fundamental matrix.
Definition at line 890 of file stereoCamera.cpp.
Referenced by estimateEssential().
{
    Mat F_true(3,3,CV_64FC1);
    Mat X1(2,4,CV_64FC1);
    Mat X2(2,4,CV_64FC1);
    Mat X3(2,4,CV_64FC1);
    Mat Y1(2,4,CV_64FC1);
    Mat Y2(2,4,CV_64FC1);
    Mat Y3(2,4,CV_64FC1);
    for(int i=0; i<P1.rows; i++)
    {
        for(int j=0; j<P1.cols; j++)
        {
            if(i==0)
            {
                X2.at<double>(1,j)= P1.at<double>(i,j);
                X3.at<double>(0,j)= P1.at<double>(i,j);
                Y2.at<double>(1,j)= P2.at<double>(i,j);
                Y3.at<double>(0,j)= P2.at<double>(i,j);
            }
            if(i==1)
            {
                X1.at<double>(0,j)= P1.at<double>(i,j);
                X3.at<double>(1,j)= P1.at<double>(i,j);
                Y1.at<double>(0,j)= P2.at<double>(i,j);
                Y3.at<double>(1,j)= P2.at<double>(i,j);
            }
            if(i==2)
            {
                X1.at<double>(1,j)= P1.at<double>(i,j);
                X2.at<double>(0,j)= P1.at<double>(i,j);
                Y1.at<double>(1,j)= P2.at<double>(i,j);
                Y2.at<double>(0,j)= P2.at<double>(i,j);
            }
        }
    }
    std::vector<Mat> MatX;
    std::vector<Mat> MatY;
    MatX.push_back(X1);
    MatX.push_back(X2);
    MatX.push_back(X3);
    MatY.push_back(Y1);
    MatY.push_back(Y2);
    MatY.push_back(Y3);
    for(int i=0; i<F_true.rows; i++)
    {
        for(int j=0; j<F_true.cols; j++)
        {
            Mat X=MatX[i];
            Mat Y=MatY[j];
            Mat concatenated;
            cv::vconcat(X,Y,concatenated);
            F_true.at<double>(j,i)=cv::determinant(concatenated);
        }
    }
    return F_true;
}
findMatch()
Mat StereoCamera::findMatch (bool visualize = false, double displacement = 20.0, double radius = 200.0)
It finds matches between two images.
SIFT detector and descriptor is used.
Note
Run setImages and indistortImages methods before using this method.
Parameters
visualize true if you want to visualize matches between images
displacement maximum pixel displacement between first and second camera
radius maximum radius between the first candidate match and the second one
Definition at line 750 of file stereoCamera.cpp.
References triangulation().
{
    if (this->imleftund.empty() || this->imrightund.empty())
    {
        imleftund=imleft;
        imrightund=imright;
    }
    this->PointsL.clear();
    this->PointsR.clear();
    this->InliersL.clear();
    this->InliersR.clear();
    Mat grayleft(imleftund.rows,imleftund.cols, CV_8UC1);
    imleftund.convertTo(grayleft,CV_8UC1);
    Mat grayright(imrightund.rows,imrightund.cols,CV_8UC1);
    imrightund.convertTo(grayright,CV_8UC1);
    vector<KeyPoint> keypoints1,keypoints2;
    Mat descriptors1,descriptors2;
#ifdef OPENCV_GREATER_2
    Ptr<xfeatures2d::SIFT> sift=xfeatures2d::SIFT::create();
    yAssert(sift!=NULL);
    sift->detect(grayleft,keypoints1);
    sift->compute(grayleft,keypoints1,descriptors1);
    sift->detect(grayright,keypoints2);
    sift->compute(grayright,keypoints2,descriptors2);
#else
    Ptr<cv::FeatureDetector> detector=cv::FeatureDetector::create("SIFT");
    Ptr<cv::DescriptorExtractor> descriptorExtractor=cv::DescriptorExtractor::create("SIFT");
    yAssert(detector!=NULL);
    yAssert(descriptorExtractor!=NULL);
    detector->detect(grayleft,keypoints1);
    descriptorExtractor->compute(grayleft,keypoints1,descriptors1);
    detector->detect(grayright,keypoints2);
    descriptorExtractor->compute(grayright,keypoints2,descriptors2);
#endif
    
    cv::BFMatcher descriptorMatcher;
    vector<DMatch> filteredMatches;
    crossCheckMatching(descriptorMatcher,descriptors1,descriptors2,filteredMatches,radius);
    for (size_t i=0; i<filteredMatches.size(); i++)
    {
        Point2f pointL=keypoints1[filteredMatches[i].queryIdx].pt;
        Point2f pointR=keypoints2[filteredMatches[i].trainIdx].pt;
        if (fabs(pointL.y-pointR.y)<displacement)
        {
            this->PointsR.push_back(pointR);
            this->PointsL.push_back(pointL);
        }
    }
    Mat matchImg;
    if (visualize)
        cv::drawMatches(this->imleftund,keypoints1,this->imrightund,keypoints2,
                filteredMatches,matchImg,Scalar(0,0,255,0),Scalar(0,0,255,0));
    return matchImg;
}
fromRectifiedToOriginal()
Point2f StereoCamera::fromRectifiedToOriginal (int u, int v, int camera)
Given the u,v pixel coordinates in the rectified image the method returns the position of the pixel in the non-rectified frame.
Parameters
u the x pixel coordinate in the rectified image.
v the y pixel coordinate in the rectified image.
cam cam=1 for left image, cam=2 for right image.
Returns
the pixel position in the non-rectified image.
Definition at line 722 of file stereoCamera.cpp.
{
    cv::Point2f originalPoint;
    if(u>=map11.rows || u<0 || v>=map12.cols || v< 0)
    {
        originalPoint.x=0;
        originalPoint.y=0;
        return originalPoint;
    }
    if(camera==LEFT)
    {
        originalPoint.x=map11.ptr<float>(v)[u];
        originalPoint.y=map12.ptr<float>(v)[u];
    }
    else
    {
        originalPoint.x=map21.ptr<float>(v)[u];
        originalPoint.y=map22.ptr<float>(v)[u];
    }
    return originalPoint;
}
getDisparity()
const Mat & StereoCamera::getDisparity () const
It returns the disparity image.
Returns
the disparity image computed via computeDisparity(). The image is 8 bit unsigned.
Definition at line 533 of file stereoCamera.cpp.
                                            {
    return this->Disparity;
}
getDisparity16()
const Mat & StereoCamera::getDisparity16 () const
It returns the disparity image.
Returns
the disparity image computed via computeDisparity(). The image is 16 bit signed.
Definition at line 538 of file stereoCamera.cpp.
Referenced by metricTriangulation().
                                              {
    return this->Disparity16;
}
getDistCoeffLeft()
const Mat & StereoCamera::getDistCoeffLeft () const
It returns the 5x1 left distortion coefficients.
Returns
5x1 left distortion coefficients.
Definition at line 2283 of file stereoCamera.cpp.
{
    return this->DistL;
}
getDistCoeffRight()
const Mat & StereoCamera::getDistCoeffRight () const
It returns the 5x1 right distortion coefficients.
Returns
5x1 right distortion coefficients.
Definition at line 2289 of file stereoCamera.cpp.
{
    return this->DistR;
}
getDistortedPixel()
Point2f StereoCamera::getDistortedPixel (int u, int v, int cam = 1)
Given the u,v pixel coordinates in the undistorted image the method returns the original position of the pixel in the distorted frame.
Parameters
u the x pixel coordinate in the undistorted image.
v the y pixel coordinate in the undistorted image.
cam cam=1 for left image, cam=2 for right image.
Returns
the pixel position in the distorted image.
Definition at line 2305 of file stereoCamera.cpp.
{
    Point2f distortedPixel;
    Mat MapperX,MapperY;
    if(cam==LEFT)
    {
        MapperX=mapxL;
        MapperY=mapyL;
    }
    else
    {
        MapperX=mapxR;
        MapperY=mapyR;
    }
    distortedPixel.x=MapperX.ptr<float>(v)[u];
    distortedPixel.y=MapperY.ptr<float>(v)[u];
    return distortedPixel;
}
getFundamental()
const Mat & StereoCamera::getFundamental () const
It returns the 3x3 fundamental matrix.
Returns
3x3 fundamental matrix.
Definition at line 1495 of file stereoCamera.cpp.
                                              {
    return this->F;
}
getImLeft()
const Mat & StereoCamera::getImLeft () const
It returns the left (first) image.
Returns
the left (first) image.
Definition at line 523 of file stereoCamera.cpp.
Referenced by updateMappings().
                                         {
    return this->imleft;
}
getImLeftUnd()
const Mat & StereoCamera::getImLeftUnd () const
It returns the left undistorted image.
Returns
the left undistorted image.
Definition at line 1490 of file stereoCamera.cpp.
                                            {
    return this->imleftund;
}
getImRight()
const Mat & StereoCamera::getImRight () const
It returns the right (second) image.
Returns
the right (second) image.
Definition at line 528 of file stereoCamera.cpp.
                                          {
    return this->imright;
}
getImRightUnd()
const Mat & StereoCamera::getImRightUnd () const
It returns the right undistorted image.
Returns
the right undistorted image.
Definition at line 1500 of file stereoCamera.cpp.
                                             {
    return this->imrightund;
}
getKleft()
const Mat & StereoCamera::getKleft () const
It returns the 3x3 left camera matrix.
Returns
3x3 left camera matrix.
Definition at line 96 of file stereoCamera.cpp.
                                        {
    return this->Kleft;
}
getKright()
const Mat & StereoCamera::getKright () const
It returns the 3x3 right camera matrix.
Returns
3x3 right camera matrix.
Definition at line 101 of file stereoCamera.cpp.
                                         {
    return this->Kright;
}
getLRectified()
const Mat & StereoCamera::getLRectified () const
The method returns the first rectified image.
Returns
The first rectified image.
Definition at line 2161 of file stereoCamera.cpp.
{
    return this->imgLeftRect;
}
getMapperL()
const Mat & StereoCamera::getMapperL () const
It returns the mapping between the original left camera and the rectified left camera.
Returns
a 16 bit signed 2 channel image containing the mapping from the original left camera to the rectified left camera.
Definition at line 1915 of file stereoCamera.cpp.
Referenced by metricTriangulation().
                                          {
    return this->MapperL;
}
getMapperR()
const Mat & StereoCamera::getMapperR () const
It returns the mapping between the original right camera and the rectified right camera.
Returns
a 16 bit signed 2 channel image containing the mapping from the original right camera to the rectified right camera.
Definition at line 1920 of file stereoCamera.cpp.
                                          {
    return this->MapperR;
}
getMatchLeft()
const vector< Point2f > & StereoCamera::getMatchLeft () const
It returns the pixel coordinates of the matches in the left image.
Returns
pixel coordinates of the matches in the left image.
Definition at line 106 of file stereoCamera.cpp.
                                                        {
    return this->InliersL;
}
getMatchRight()
const vector< Point2f > & StereoCamera::getMatchRight () const
It returns the pixel coordinates of the matches in the right image.
Returns
pixel coordinates of the matches in the right image.
Definition at line 111 of file stereoCamera.cpp.
                                                         {
    return this->InliersR;
}
getQ()
const Mat & StereoCamera::getQ () const
It returns the 4x4 disparity-to-depth mapping matrix.
Returns
4x4 disparity-to-depth mapping matrix.
Definition at line 543 of file stereoCamera.cpp.
                                    {
    return this->Q;
}
getRLrect()
const Mat & StereoCamera::getRLrect () const
It returns the rotation matrix between the original left camera and the rectified left camera.
Returns
3x3 rotation matrix between the original left camera and the rectified left camera.
Definition at line 1905 of file stereoCamera.cpp.
Referenced by computeWorldImage(), metricTriangulation(), and triangulateKnownDisparity().
                                         {
    return this->RLrect;
}
getRotation()
const Mat & StereoCamera::getRotation () const
It returns the rotation matrix between the two cameras.
Returns
3x3 rotation matrix between the first and the second camera.
Definition at line 1596 of file stereoCamera.cpp.
Referenced by horn().
                                           {
    return this->R;
}
getRRectified()
const Mat & StereoCamera::getRRectified () const
The method returns the second rectified image.
Returns
The second rectified image.
Definition at line 2167 of file stereoCamera.cpp.
{
    return this->imgRightRect;
}
getRRrect()
const Mat & StereoCamera::getRRrect () const
It returns the rotation matrix between the original right camera and the rectified right camera.
Returns
3x3 rotation matrix between the original right camera and the rectified right camera.
Definition at line 1910 of file stereoCamera.cpp.
                                         {
    return this->RRrect;
}
getTranslation()
const Mat & StereoCamera::getTranslation () const
It returns the translation vector between the two cameras.
Returns
3x1 translation matrix between the first and the second camera.
Definition at line 1591 of file stereoCamera.cpp.
                                              {
    return this->T;
}
horn()
void StereoCamera::horn (Mat & K1, Mat & K2, vector< Point2f > & Points1, vector< Point2f > & Points2, Mat & Rot, Mat & Tras)
It performs the horn relative orientations algorithm i.e.
it estimates the motion from one camera to another one using a initial guess. A good initial guess can be obtained using the essentialDecomposition method.
Parameters
K1 3x3 matrix with intrinsic parameters of the first camera
K2 3x3 matrix with intrinsic parameters of the second camera
Points1 matches in the first image
Points2 matches in the second image
Rot initial rotation (3x3 matrix) guess. The new output rotation is stored here
Tras initial translation (3x1 matrix) guess. The new output translation is stored here
Definition at line 1697 of file stereoCamera.cpp.
References getRotation().
Referenced by hornRelativeOrientations().
                                                                                                           
              {
    double prevres = 1E40;
    double res = 1E39;
    double vanishing = 1E-16;
    Tras=Tras/norm(Tras);
    normalizePoints(K1,K2,PointsL,PointsR);
    int iters=0;
    Mat B(3,3,CV_64FC1);
    Mat C(3,3,CV_64FC1);
    Mat D(3,3,CV_64FC1);
    Mat cs(3,1,CV_64FC1);
    Mat ds(3,1,CV_64FC1);
    Mat r1(3,1,CV_64FC1);
    Mat r2(3,1,CV_64FC1);
    while ((prevres - res > vanishing)) {
        iters = iters+1;
        B.setTo(0);
        C.setTo(0);
        D.setTo(0);
        cs.setTo(0);
        ds.setTo(0);
        prevres=res;
        res=0;
        for(int i=0; i<(int) PointsL.size(); i++) {
            r1.at<double>(0,0)=PointsL[i].x;
            r1.at<double>(1,0)=PointsL[i].y;
            r1.at<double>(2,0)=1;
            r1=r1/norm(r1);
            r2.at<double>(0,0)=PointsR[i].x;
            r2.at<double>(1,0)=PointsR[i].y;
            r2.at<double>(2,0)=1;
            r2=r2/norm(r2);
            Mat r1p= Rot*r1;
            Mat ci=r1p.cross(r2);
            Mat di=r1p.cross(r2.cross(Tras));
            Mat si=Tras.t()*ci;
            B=B+(ci*di.t());
            D=D+(di*di.t());
            C=C+(ci*ci.t());
            cs=cs+ (si.at<double>(0,0)*ci);
            ds=ds+ (si.at<double>(0,0)*di);
            Mat residual=Tras.t()*ci*ci.t()*Tras;
            res=res+residual.at<double>(0,0);
        }
        Mat L(7,7,CV_64FC1);
        L.setTo(0);
        for(int i=0; i<3; i++)
            for(int j=0; j<3; j++)
                L.at<double>(i,j)=C.at<double>(i,j);
        for(int i=0; i<3; i++)
            for(int j=3; j<6; j++)
                L.at<double>(i,j)=B.at<double>(i,j-3);
        for(int i=0; i<3; i++)
            L.at<double>(i,6)=Tras.at<double>(i,0);
        for(int i=3; i<6; i++)
            for(int j=0; j<3; j++) {
                Mat Bt=B.t();
                L.at<double>(i,j)=Bt.at<double>(i-3,j);
            }
        for(int i=3; i<6; i++)
            for(int j=3; j<6; j++)
                L.at<double>(i,j)=D.at<double>(i-3,j-3);
        for(int j=0; j<3; j++) {
            Mat Trast=Tras.t();
            L.at<double>(6,j)=Trast.at<double>(0,j);
        }
        Mat Y(7,1,CV_64FC1);
        Y.setTo(0);
        for(int j=0; j<3; j++)
            Y.at<double>(j,0)=-cs.at<double>(j,0);
        for(int j=3; j<6; j++)
            Y.at<double>(j,0)=-ds.at<double>(j-3,0);
        Mat Linv=L.inv();
        Mat result=Linv*Y;
        Tras=Tras+result(Range(0,3),Range(0,1));
        Tras=Tras/norm(Tras);
        Mat q(4,1,CV_64FC1);
        Mat temp=result(Range(3,6),Range(0,1));
        q.at<double>(0,0)= sqrt(1-(0.25* norm(temp)*norm(temp)));
        q.at<double>(1,0)= 0.5*result.at<double>(3,0);
        q.at<double>(2,0)= 0.5*result.at<double>(4,0);
        q.at<double>(3,0)= 0.5*result.at<double>(5,0);
        Mat deltaR(3,3,CV_64FC1);
        getRotation(q,deltaR);
        Rot=deltaR*Rot;
        SVD dec(Rot);
        Mat Id = Mat::eye(3, 3, CV_64F);
        Mat Vt=dec.vt;
        Mat U=dec.u;
        Rot=U*Id*Vt;
    }
}
hornRelativeOrientations()
void StereoCamera::hornRelativeOrientations ()
It performs the horn relative orientations, all the parameters are assumed initialized in the StereoCamera object.
The new output Rotation and Translation matrices are stored in the R and T members.
Definition at line 1635 of file stereoCamera.cpp.
References horn().
                                            {
    if(this->PointsL.size()<10 || this->PointsR.size()<10) {
        cout << "No matches found! Run findMatch fist!" << endl;
        return;
    }
    if(this->Kleft.empty() || this->Kright.empty() || this->R.empty() || this->T.empty()) {
        cout << "Cameras are empty, run Calibration first" << endl;
        return;
    }
    if(InliersL.empty()) {
        InliersL=PointsL;
        InliersR=PointsR;
    }
    Mat Rot=this->R.clone();
    Mat Tras=this->T.clone();
    horn(this->Kleft,this->Kright,this->InliersL,this->InliersR,Rot,Tras);
    this->R=Rot.clone();
    this->Rinit=Rot.clone();
    this->T=Tras/norm(Tras)*norm(T);
    this->Tinit=Tras/norm(Tras)*norm(Tinit);
    this->updatePMatrix();
}
initELAS()
void StereoCamera::initELAS (yarp::os::ResourceFinder & rf)
Initialization of ELAS parameters.
Parameters
rf The ResourceFinder mechanism is used to set the parameters either to the default value or to the value passed by the user via command line. See the documentation of the SFM module to get the list of parameters that are processed by this initialization function.
Definition at line 164 of file stereoCamera.cpp.
{
    use_elas = true;
    string elas_string = rf.check("elas_setting",Value("ROBOTICS")).asString();
    double disp_scaling_factor = rf.check("disp_scaling_factor",Value(1.0)).asDouble();
    elaswrap = new elasWrapper(disp_scaling_factor, elas_string);
    if (rf.check("elas_subsampling"))
        elaswrap->set_subsampling(true);
    if (rf.check("elas_add_corners"))
        elaswrap->set_add_corners(true);
    elaswrap->set_ipol_gap_width(40);
    if (rf.check("elas_ipol_gap_width"))
        elaswrap->set_ipol_gap_width(rf.find("elas_ipol_gap_width").asInt());
    if (rf.check("elas_support_threshold"))
        elaswrap->set_support_threshold(rf.find("elas_support_threshold").asDouble());
    if(rf.check("elas_gamma"))
        elaswrap->set_gamma(rf.find("elas_gamma").asDouble());
    if (rf.check("elas_sradius"))
        elaswrap->set_sradius(rf.find("elas_sradius").asDouble());
    if (rf.check("elas_match_texture"))
        elaswrap->set_match_texture(rf.find("elas_match_texture").asInt());
    if (rf.check("elas_filter_median"))
        elaswrap->set_filter_median(rf.find("elas_filter_median").asBool());
    if (rf.check("elas_filter_adaptive_mean"))
        elaswrap->set_filter_adaptive_mean(rf.find("elas_filter_adaptive_mean").asBool());
    cout << endl << "ELAS parameters:" << endl << endl;
    cout << "disp_scaling_factor: " << disp_scaling_factor << endl;
    cout << "setting: " << elas_string << endl;
    cout << "postprocess_only_left: " << elaswrap->get_postprocess_only_left() << endl;
    cout << "subsampling: " << elaswrap->get_subsampling() << endl;
    cout << "add_corners: " << elaswrap->get_add_corners() << endl;
    cout << "ipol_gap_width: " << elaswrap->get_ipol_gap_width() << endl;
    cout << "support_threshold: " << elaswrap->get_support_threshold() << endl;
    cout << "gamma: " << elaswrap->get_gamma() << endl;
    cout << "sradius: " << elaswrap->get_sradius() << endl;
    cout << "match_texture: " << elaswrap->get_match_texture() << endl;
    cout << "filter_median: " << elaswrap->get_filter_median() << endl;
    cout << "filter_adaptive_mean: " << elaswrap->get_filter_adaptive_mean() << endl;
    cout << endl;
}
metricTriangulation() [1/2]
Point3f StereoCamera::metricTriangulation (Point2f & point1, double thMeters = 10)
It performs the metric triangulation given the pixel coordinates on the first image.
Run compute disparity before using this method.
Parameters
point1 the pixel coordinates in the first image.
Returns
a metric 3D point w.r.t. the first camera reference system.
Definition at line 1954 of file stereoCamera.cpp.
References getDisparity16(), and getMapperL().
                                                                          {
    lock_guard<mutex> lg(mtx);
    if(Q.empty() || Disparity16.empty()) {
        cout << "Run computeDisparity() method first!" << endl;
        Point3f point;
        point.x=0.0;
        point.y=0.0;
        point.z=0.0;
        return point;
    }
    int u=(int) point1.x;
    int v=(int) point1.y;
    Point3f point;
    // Mapping from Rectified Cameras to Original Cameras
    Mat Mapper=this->getMapperL();
    if(Mapper.empty()) {
        point.x=0.0;
        point.y=0.0;
        point.z=0.0;
        return point;
    }
    float usign=Mapper.ptr<float>(v)[2*u];
    float vsign=Mapper.ptr<float>(v)[2*u+1];
    u=cvRound(usign);
    v=cvRound(vsign);
    const cv::Mat& disp16=this->getDisparity16();
    if(u<0 || u>=disp16.size().width || v<0 || v>=disp16.size().height) {
        point.x=0.0;
        point.y=0.0;
        point.z=0.0;
        return point;
    }
    CvScalar scal=cvGet2D(&disp16,v,u);
    double disparity=scal.val[0]/16.0;
    float w= (float) ((float) disparity*Q.at<double>(3,2)) + ((float)Q.at<double>(3,3));
    point.x= (float)((float) (usign+1)*Q.at<double>(0,0)) + ((float) Q.at<double>(0,3));
    point.y=(float)((float) (vsign+1)*Q.at<double>(1,1)) + ((float) Q.at<double>(1,3));
    point.z=(float) Q.at<double>(2,3);
    point.x=point.x/w;
    point.y=point.y/w;
    point.z=point.z/w;
    // discard points far more than thMeters meters or with not valid disparity (<0)
    if(point.z>thMeters || point.z<0) {
        point.x=0.0;
        point.y=0.0;
        point.z=0.0;
    }
    else {
        Mat P(3,1,CV_64FC1);
        P.at<double>(0,0)=point.x;
        P.at<double>(1,0)=point.y;
        P.at<double>(2,0)=point.z;
        // Rototranslation from rectified camera to original camera
        P=this->getRLrect().t()*P;
        point.x=(float) P.at<double>(0,0);
        point.y=(float) P.at<double>(1,0);
        point.z=(float) P.at<double>(2,0);
    }
    return point;
}
metricTriangulation() [2/2]
Point3f StereoCamera::metricTriangulation (Point2f & point1, Mat & H, double thMeters = 10)
It performs the metric triangulation given the pixel coordinates on the first image.
The 3D Point is w.r.t the system defined by the parameter H. Run compute disparity before using this method.
Parameters
point1 the pixel coordinates in the first image.
H the 4x4 rototranslation matrix of the system.
Returns
a metric 3D point w.r.t. the reference system defined by H.
Definition at line 2030 of file stereoCamera.cpp.
References getDisparity16(), getMapperL(), and getRLrect().
                                                                                  {
    lock_guard<mutex> lg(mtx);
    if(H.empty())
        H=H.eye(4,4,CV_64FC1);
    if(Q.empty() || Disparity16.empty()) {
        cout << "Run computeDisparity() method first!" << endl;
        Point3f point;
        point.x=0.0;
        point.y=0.0;
        point.z=0.0;
        return point;
    }
    int u=(int) point1.x; // matrix starts from (0,0), pixels from (1,1)
    int v=(int) point1.y;
    Point3f point;
    // Mapping from Rectified Cameras to Original Cameras
    Mat Mapper=this->getMapperL();
    if(Mapper.empty()) {
        point.x=0.0;
        point.y=0.0;
        point.z=0.0;
        return point;
    }
    float usign=Mapper.ptr<float>(v)[2*u];
    float vsign=Mapper.ptr<float>(v)[2*u+1];
    u=cvRound(usign);
    v=cvRound(vsign);
    const cv::Mat& disp16=this->getDisparity16();
    if(u<0 || u>=disp16.size().width || v<0 || v>=disp16.size().height) {
        point.x=0.0;
        point.y=0.0;
        point.z=0.0;
        return point;
    }
    CvScalar scal=cvGet2D(&disp16,v,u);
    double disparity=scal.val[0]/16.0;
    float w= (float) ((float) disparity*Q.at<double>(3,2)) + ((float)Q.at<double>(3,3));
    point.x= (float)((float) (usign+1)*Q.at<double>(0,0)) + ((float) Q.at<double>(0,3));
    point.y=(float)((float) (vsign+1)*Q.at<double>(1,1)) + ((float) Q.at<double>(1,3));
    point.z=(float) Q.at<double>(2,3);
    point.x=point.x/w;
    point.y=point.y/w;
    point.z=point.z/w;
    // discard points far more than thMeters meters or with not valid disparity (<0)
    if(point.z>thMeters || point.z<0) {
        point.x=0.0;
        point.y=0.0;
        point.z=0.0;
        return point;
    }
    Mat RLrectTmp=this->getRLrect().t();
    Mat Tfake = Mat::zeros(0,3,CV_64F);
    Mat P(4,1,CV_64FC1);
    P.at<double>(0,0)=point.x;
    P.at<double>(1,0)=point.y;
    P.at<double>(2,0)=point.z;
    P.at<double>(3,0)=1;
    Mat Hrect=buildRotTras(RLrectTmp,Tfake);
    P=H*Hrect*P;
    point.x=(float) ((float) P.at<double>(0,0)/P.at<double>(3,0));
    point.y=(float) ((float) P.at<double>(1,0)/P.at<double>(3,0));
    point.z=(float) ((float) P.at<double>(2,0)/P.at<double>(3,0));
    return point;
}
projectPoints3D()
vector< Point2f > StereoCamera::projectPoints3D (string camera, vector< Point3f > & points3D, Mat & H)
The method returns the 2D projection of a set of 3D points in the cartesian space to the specified camera.
Parameters
camera `left` or `right` camera
point3D the list of the 3D position in the reference frame H
H the transformation from the camera reference system to the H reference system
Returns
The 2D positions.
Definition at line 2173 of file stereoCamera.cpp.
{
    vector<Point2f> points2D;
    if(this->Kleft.empty() || this->DistL.empty() || this->Kright.empty() || this->DistR.empty()) {
        cout <<" Cameras are not calibrated! Run the Calibration first!" << endl;
        return points2D;
    }
    if(H.empty())
        H=H.eye(4,4,CV_64FC1);
    lock_guard<mutex> lg(mtx);
    for (int i=0; i<points3D.size(); i++)
    {
        // Apply inverse Trasformation for each point
        Point3f point=points3D[i];
        Mat P(4,1,CV_64FC1);
        P.at<double>(0,0)=point.x;
        P.at<double>(1,0)=point.y;
        P.at<double>(2,0)=point.z;
        P.at<double>(3,0)=1;
        P=H.inv()*P;
        point.x=(float) ((float) P.at<double>(0,0)/P.at<double>(3,0));
        point.y=(float) ((float) P.at<double>(1,0)/P.at<double>(3,0));
        point.z=(float) ((float) P.at<double>(2,0)/P.at<double>(3,0));
        points3D[i]=point;
    }
    Mat cameraMatrix, distCoeff, rvec, tvec;
    rvec=Mat::zeros(3,1,CV_64FC1);
    if(camera=="left")
    {
        cameraMatrix=this->Kleft;
        distCoeff=this->DistL;
        Mat R2= Mat::eye(3,3,CV_64FC1);
        Rodrigues(R2,rvec);
        tvec=Mat::zeros(3,1,CV_64FC1);
    }
    else
    {
        cameraMatrix=this->Kright;
        distCoeff=this->DistR;
        Mat R2= this->R;
        Rodrigues(R2,rvec);
        tvec=this->T;
    }
    Mat points3Mat(points3D);
    projectPoints(points3Mat,rvec,tvec,cameraMatrix,distCoeff,points2D);
    return points2D;
}
rectifyImages()
void StereoCamera::rectifyImages ()
The method rectifies the two images: it transform each image plane such that pairs conjugate epipolar lines become collinear and parallel to one of the image axes (i.e.
there is 0 disparity on the Y axis).
Definition at line 548 of file stereoCamera.cpp.
{
    if(this->Kleft.empty() || this->DistL.empty() || this->Kright.empty() || this->DistR.empty()) {
        cout <<" Cameras are not calibrated! Run the Calibration first!" << endl;
        return;
    }
    if(this->imleft.empty() || this->imright.empty()) {
        cout << "Images are not set! set the images first!" << endl;
        return;
    }
    Size img_size = this->imleft.size();
    if(cameraChanged)
    {
        lock_guard<mutex> lg(mtx);
        stereoRectify(this->Kleft, this->DistL, this->Kright, this->DistR, img_size, this->R, this->T,
      this->RLrect, this->RRrect, this->PLrect, this->PRrect, this->Q, -1);
    }
    if(cameraChanged)
    {
        initUndistortRectifyMap(this->Kleft, this->DistL, this->RLrect, this->PLrect, img_size, CV_32FC1,
      this->map11, this->map12);
        initUndistortRectifyMap(this->Kright, this->DistR, this->RRrect, this->PRrect, img_size, CV_32FC1,
       this->map21, this->map22);
    }
    remap(this->imleft, this->imgLeftRect, this->map11, this->map12, cv::INTER_LINEAR);
    remap(this->imright, this->imgRightRect, this->map21,this->map22, cv::INTER_LINEAR);
    cameraChanged = false;
}
remapDisparity()
cv::Mat StereoCamera::remapDisparity (cv::Mat disp)
Remaps the disparity map on the basis of the mapping previously computed.
Parameters
disp the disparity map to be remapped
Returns
the remapped disparity map
Definition at line 2423 of file stereoCamera.cpp.
{
    cv::Mat remapped;
    Mat x;
    remap(disp,remapped,this->MapperL,x,cv::INTER_LINEAR);
    remapped.convertTo(remapped,CV_8U);
    return remapped;
}
saveCalibration()
void StereoCamera::saveCalibration (string extrinsicFilePath, string intrinsicFilePath)
It saves the calibration.
Parameters
extrinsicFilePath the path of the extrinsic parameters file
intrinsicFilePath the path of the intrinsic parameters file
Definition at line 470 of file stereoCamera.cpp.
                                                                                     {
    if(Kleft.empty() || Kright.empty() || DistL.empty() || DistR.empty() || R.empty() || T.empty()) {
        std::cout << "Error: cameras are not calibrated! Run the calibration or set intrinsic and extrinsic
       parameters" << std::endl;
        return;
    }
    FileStorage fs(intrinsicFilePath+".yml", FileStorage::WRITE);
    if(fs.isOpened())
    {
        fs << "M1" << Kleft << "D1" << DistL << "M2" << Kright << "D2" << DistR;
        fs.release();
    }
    else
        cout << "Error: can not save the intrinsic parameters\n";
    fs.open(extrinsicFilePath+".yml", FileStorage::WRITE);
    if(fs.isOpened())
    {
        fs << "R" << R << "T" << T <<"Q" << Q;
        fs.release();
    }
    else
        std::cout << "Error: can not save the intrinsic parameters" << std::endl;
    ofstream fout((intrinsicFilePath+".ini").c_str());
    // Left Eye
    fout << "[left]" << endl;
    fout << "fx " << Kleft.at<double>(0,0) << endl;
    fout << "fy " << Kleft.at<double>(1,1) << endl;
    fout << "cx " << Kleft.at<double>(0,2) << endl;
    fout << "cy " << Kleft.at<double>(1,2) << endl;
    fout << "k1 " << DistL.at<double>(0,0) << endl;
    fout << "k2 " << DistL.at<double>(1,0) << endl;
    fout << "p1 " << DistL.at<double>(2,0) << endl;
    fout << "p2 " << DistL.at<double>(3,0) << endl;
    // Right Eye
    fout << "[right]" << endl;
    fout << "fx " << Kright.at<double>(0,0) << endl;
    fout << "fy " << Kright.at<double>(1,1) << endl;
    fout << "cx " << Kright.at<double>(0,2) << endl;
    fout << "cy " << Kright.at<double>(1,2) << endl;
    fout << "k1 " << DistR.at<double>(0,0) << endl;
    fout << "k2 " << DistR.at<double>(1,0) << endl;
    fout << "p1 " << DistR.at<double>(2,0) << endl;
    fout << "p2 " << DistR.at<double>(3,0) << endl;
    fout.close();
}
setExpectedPosition()
void StereoCamera::setExpectedPosition (Mat & Rot, Mat & Tran)
The function set the expected Rotation and Translation parameters for the current image pair.
They can be computed using the Kinematics.
Parameters
Rot 3x3 matrix representing the rotation between the left and the right camera.
Tran 3x1 vector representing the translation between the left and the right camera.
Definition at line 2416 of file stereoCamera.cpp.
{
    R_exp=Rot;
    T_exp=Tran;
}
setImages()
void StereoCamera::setImages (const Mat & firstImg, const Mat & secondImg)
It stores in memory a couple of images.
Parameters
firstImg the images acquired from the first (main) camera
secondImg the images acquired from the second (secondary) camera
Definition at line 231 of file stereoCamera.cpp.
                                                              {
    this->imleft=left;
    this->imright=right;
}
setIntrinsics()
void StereoCamera::setIntrinsics (Mat & K1, Mat & K2, Mat & Dist1, Mat & Dist2)
It sets the intrinsic parameters.
Parameters
K1 3x3 camera matrix of the first camera.
K2 3x3 camera matrix of the second camera.
Dist1 4x1 distortion coefficients vector of the first camera.
Dist2 4x1 distortion coefficients vector of the second camera.
Definition at line 1940 of file stereoCamera.cpp.
Referenced by StereoCamera().
                                                                         {
    lock_guard<mutex> lg(mtx);
    this->Kleft=KL;
    this->Kright=KR;
    this->DistL=DistL;
    this->DistR=DistR;
    if(!this->R.empty() && !this->T.empty())
        updatePMatrix();
    this->cameraChanged=true;
    buildUndistortRemap();
}
setMatches()
void StereoCamera::setMatches (std::vector< cv::Point2f > & pointsL, std::vector< cv::Point2f > & pointsR)
The function initialize the matches of the current image pair.
For example matches can be computed in GPU with higher framerate.
Parameters
pointsL vector of Point2f representing the keypoints on the left image.
pointsR vector of Point2f representing the keypoints on the right image.
Definition at line 2408 of file stereoCamera.cpp.
{
    PointsL=pointsL;
    PointsR=pointsR;
}
setRotation()
void StereoCamera::setRotation (Mat & Rot, int mode = 0)
It sets the rotation matrix (if known) between the first and the second camera.
Parameters
Rot the 3x3 rotation matrix.
mode the following values are allowed: mode=0 the rotation matrix R is set equal to Rot. mode=1 the rotation matrix R is set equal to Rot*R. mode=2 the rotation matrix R is set equal to Rot*Rinit.
Definition at line 1505 of file stereoCamera.cpp.
Referenced by StereoCamera().
                                                {
    lock_guard<mutex> lg(mtx);
    if(mul==0)
        this->R=Rot;
    if(mul==1)
        this->R=Rot*R;
    if(mul==2)
        this->R=Rot*Rinit;
    if(R_exp.empty())
        R_exp=R;
    this->updatePMatrix();
    this->cameraChanged=true;
}
setTranslation()
void StereoCamera::setTranslation (Mat & Tras, int mul = 0)
It sets the translation vector (if known) between the first and the second camera.
Parameters
Tras the 3x1 translation matrix.
mode the following values are allowed: mode=0 the translation vector T is set equal to Tras. mode=1 the translation vector T is set equal to Tras+T. mode=2 the translation vector T is set equal to Tras+Tinit.
Definition at line 1521 of file stereoCamera.cpp.
Referenced by StereoCamera().
                                                    {
    lock_guard<mutex> lg(mtx);
    if(mul==0)
        this->T=Tras;
    if(mul==1)
        this->T=Tras+T;
    if(mul==2)
        this->T=Tras+Tinit;
    if(T_exp.empty())
        T_exp=T;
    if(!this->Kleft.empty() && !this->Kright.empty())
        this->updatePMatrix();
    this->cameraChanged=true;
}
stereoCalibration()
void StereoCamera::stereoCalibration (vector< string > imageList, int boardWidth, int boardHeight, float sqsize = 1.0)
It performs the stereo camera calibration.
(see stereoCalibration module)
Parameters
imageList is the list containing the paths of the images with the chessboard patterns. even indices refer to Left camera images (i.e. main camera images), while odd indices refer to Right camera images.
boardWidth the number of inner corners in the width direction of the chess board pattern (see stereoCalibration module)
boardHeight the number of inner corners in the height direction of the chess board pattern (see stereoCalibration module)
sqsize the size of the square of the chess board pattern. It is needed for a metric reconstruction.
Definition at line 250 of file stereoCamera.cpp.
                                                                                                           
      {
    Size boardSize;
    boardSize.width=boardWidth;
    boardSize.height=boardHeight;
    runStereoCalib(imagelist, boardSize,sqsize);
}
triangulateKnownDisparity()
Point3f StereoCamera::triangulateKnownDisparity (float u, float v, float d, Mat & H)
It performs the metric triangulation given the pixel coordinates on the first image and the disparity between the two RECTIFIED images.
The 3D Point is w.r.t the system defined by the parameter H.
Parameters
u the pixel x coordinate in the first image.
v the pixel y coordinate in the first image.
d the disparity on the x coordinate between the two rectified images.
H the 4x4 rototranslation matrix of the system can be an empty matrix.
Returns
a metric 3D point w.r.t. the reference system defined by H.
Definition at line 2113 of file stereoCamera.cpp.
References getRLrect().
{
    lock_guard<mutex> lg(mtx);
    if(Q.empty())
    {
        cout << "Run rectifyImages() method first!" << endl;
        Point3f point;
        point.x=0.0;
        point.y=0.0;
        point.z=0.0;
        return point;
    }
    if(H.empty())
        H=H.eye(4,4,CV_64FC1);
    Point3f point;
    float w= (float) ((float) d*Q.at<double>(3,2)) + ((float)Q.at<double>(3,3));
    point.x= (float)((float) (u)*Q.at<double>(0,0)) + ((float) Q.at<double>(0,3));
    point.y=(float)((float) (v)*Q.at<double>(1,1)) + ((float) Q.at<double>(1,3));
    point.z=(float) Q.at<double>(2,3);
    // Rectified Camera System
    point.x=point.x/w;
    point.y=point.y/w;
    point.z=point.z/w;
    // We transform to H Coordinate System
    Mat RLrectTmp=this->getRLrect().t(); // First it transform the point to the unrectified camera
       reference system
    Mat Tfake = Mat::zeros(0,3,CV_64F);
    Mat P(4,1,CV_64FC1);
    P.at<double>(0,0)=point.x;
    P.at<double>(1,0)=point.y;
    P.at<double>(2,0)=point.z;
    P.at<double>(3,0)=1;
    Mat Hrect=buildRotTras(RLrectTmp,Tfake);
    P=H*Hrect*P;
    point.x=(float) ((float) P.at<double>(0,0)/P.at<double>(3,0));
    point.y=(float) ((float) P.at<double>(1,0)/P.at<double>(3,0));
    point.z=(float) ((float) P.at<double>(2,0)/P.at<double>(3,0));
    return point;
}
triangulation() [1/2]
Point3f StereoCamera::triangulation (Point2f & point1, Point2f & point2)
It performs the triangulation using the stored in the internal P1 and P2 3x4 Camera Matrices.
The triangulation obtained is not metric! Use the method metricTriangulation if you want a metric triangulation.
Parameters
point1 the 2D point coordinates in the first image.
point2 the 2D point coordinates in the second image.
Returns
a 3D point wrt the first camera reference system.
Definition at line 861 of file stereoCamera.cpp.
Referenced by chierality(), findMatch(), and triangulation().
                                                                           {
    Point3f point3D;
    Mat J=Mat(4,4,CV_64FC1);
    J.setTo(0);
    for(int j=0; j<4; j++) {
        int rowA=0;
        int rowB=2;
        J.at<double>(0,j)=(pointleft.x*this->Pleft.at<double>(rowB,j))- (this->Pleft.at<double>(rowA,j));
        J.at<double>(2,j)=(pointRight.x*this->Pright.at<double>(rowB,j))- (this->Pright.at<double>(rowA,j))
      ;
        rowA=1;
        J.at<double>(1,j)=(pointleft.y*this->Pleft.at<double>(rowB,j))- (this->Pleft.at<double>(rowA,j));
        J.at<double>(3,j)=(pointRight.y*this->Pright.at<double>(rowB,j))- (this->Pright.at<double>(rowA,j))
      ;
    }
    SVD decom(J);
    Mat V= decom.vt;
    point3D.x=(float) ((float) V.at<double>(3,0))/((float) V.at<double>(3,3));
    point3D.y=(float) ((float) V.at<double>(3,1))/((float) V.at<double>(3,3));
    point3D.z=(float) ((float) V.at<double>(3,2))/((float) V.at<double>(3,3));
    return point3D;
}
triangulation() [2/2]
Point3f StereoCamera::triangulation (Point2f & point1, Point2f & point2, Mat Camera1, Mat Camera2)
It performs the triangulation (HZ Chap 12.2 homogenous solution).
The triangulation obtained is not metric! Use the method metricTriangulation if you want a metric triangulation.
Parameters
point1 the 2D point coordinates in the first image.
point2 the 2D point coordinates in the second image.
Camera1 the 3x4 camera matrix of the first image.
Camera2 the 3x4 camera matrix of the second image.
Returns
a 3D point wrt the first camera reference system.
Definition at line 1370 of file stereoCamera.cpp.
References triangulation().
                                                                                                     {
    Point3f point3D;
    Mat J=Mat(4,4,CV_64FC1);
    J.setTo(0);
    for(int j=0; j<4; j++) {
        int rowA=0;
        int rowB=2;
        J.at<double>(0,j)=(pointleft.x*Camera1.at<double>(rowB,j))- (Camera1.at<double>(rowA,j));
        J.at<double>(2,j)=(pointRight.x*Camera2.at<double>(rowB,j))- (Camera2.at<double>(rowA,j));
        rowA=1;
        J.at<double>(1,j)=(pointleft.y*Camera1.at<double>(rowB,j))- (Camera1.at<double>(rowA,j));
        J.at<double>(3,j)=(pointRight.y*Camera2.at<double>(rowB,j))- (Camera2.at<double>(rowA,j));
    }
    SVD decom(J);
    Mat V= decom.vt;
    // printMatrix(V);
    /*Mat sol=Mat(4,1,CV_64FC1);
        sol.at<double>(0,0)=V.at<double>(0,0);
        sol.at<double>(1,0)=V.at<double>(1,1);
        sol.at<double>(2,0)=V.at<double>(2,2);
        sol.at<double>(3,0)=V.at<double>(3,3);
        Mat test=J*sol;
        printMatrix(test);*/
    point3D.x=(float) ((float) V.at<double>(3,0))/((float) V.at<double>(3,3));
    point3D.y=(float) ((float) V.at<double>(3,1))/((float) V.at<double>(3,3));
    point3D.z=(float) ((float) V.at<double>(3,2))/((float) V.at<double>(3,3));
    return point3D;
}
triangulationLS()
Point3f StereoCamera::triangulationLS (Point2f & point1, Point2f & point2, Mat Camera1, Mat Camera2)
It performs the least square triangulation (HZ Chap 12.2 Inhomogenous solution).
The triangulation obtained is not metric! Use the method metricTriangulation if you want a metric triangulation.
Parameters
point1 the 2D point coordinates in the first image.
point2 the 2D point coordinates in the second image.
Camera1 the 3x4 camera matrix of the first image.
Camera2 the 3x4 camera matrix of the second image.
Returns
a 3D point wrt the first camera reference system.
undistortImages()
void StereoCamera::undistortImages ()
It undistorts the images.
Note
Set undistortion coefficients before using this method.
Definition at line 1475 of file stereoCamera.cpp.
                                   {
    if(this->Kleft.empty() || this->DistL.empty() || this->Kright.empty() || this->DistR.empty()) {
        cout <<" Cameras are not calibrated! Run the Calibration first!" << endl;
        return;
    }
    if(this->imleft.empty() || this->imright.empty()) {
        cout << "Images are not set! set the images first!" << endl;
        return;
    }
    undistort(this->imleft,this->imleftund,this->Kleft,this->DistL);
    undistort(this->imright,this->imrightund,this->Kright,this->DistR);
}
updateMappings()
void StereoCamera::updateMappings ()
XXXXXXXXXXXXXXXXXXXX.
Returns
XXXXXXXXXXXXXXXXXXXX
Definition at line 2437 of file stereoCamera.cpp.
References getImLeft().
{
    int rows = this->getImLeft().rows;
    int cols = this->getImLeft().cols;
    if (cameraChanged)
    {
        std::lock_guard<std::mutex> lock(mtx);
        Mat inverseMapL(rows*cols,1,CV_32FC2);
        Mat inverseMapR(rows*cols,1,CV_32FC2);
        for (int y=0; y<rows; y++)
        {
            for (int x=0; x<cols; x++)
            {
                inverseMapL.ptr<float>(y*cols+x)[0]=(float)x;
                inverseMapL.ptr<float>(y*cols+x)[1]=(float)y;
                inverseMapR.ptr<float>(y*cols+x)[0]=(float)x;
                inverseMapR.ptr<float>(y*cols+x)[1]=(float)y;
            }
        }
        undistortPoints(inverseMapL,inverseMapL,this->Kleft,this->DistL,this->RLrect,this->PLrect);
        undistortPoints(inverseMapR,inverseMapR,this->Kright,this->DistR,this->RRrect,this->PRrect);
        Mat mapperL=inverseMapL.reshape(2,rows);
        Mat mapperR=inverseMapR.reshape(2,rows);
        this->MapperL=mapperL;
        this->MapperR=mapperR;
    }
}
The documentation for this class was generated from the following files:
/home/runner/work/stereo-vision/stereo-vision/gh-pages/lib/include/iCub/stereoVision/stereoCamera.h
/home/runner/work/stereo-vision/stereo-vision/gh-pages/lib/src/stereoCamera.cpp